============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- C:\Users\gustavo.borges\AppData\Local\Programs\Python\Python37\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\gustavo.borges\codenation\data-science-3
collecting ... collected 4 items

test_submit.py::test_q1 PASSED                                           [ 25%]
test_submit.py::test_q2 PASSED                                           [ 50%]
test_submit.py::test_q3 PASSED                                           [ 75%]
test_submit.py::test_q4 PASSED                                           [100%]

============================== warnings summary ===============================
C:\Users\gustavo.borges\AppData\Local\Programs\Python\Python37\lib\site-packages\ipywidgets\widgets\widget_selection.py:9
C:\Users\gustavo.borges\AppData\Local\Programs\Python\Python37\lib\site-packages\ipywidgets\widgets\widget_selection.py:9
  C:\Users\gustavo.borges\AppData\Local\Programs\Python\Python37\lib\site-packages\ipywidgets\widgets\widget_selection.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping, Iterable

test_submit.py::test_q4
  C:\Users\gustavo.borges\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated xml file: C:\Users\gustavo.borges\codenation\data-science-3\output.xml -
==================== 4 passed, 3 warnings in 4.77 seconds =====================
